# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='address',
            field=models.CharField(max_length=254),
        ),
    ]
