# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0004_auto_20170617_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('address', 'word')]),
        ),
    ]
